asset: awscred_darwin_amd64.tar.gz
tap: hanjunlee/homebrew-awscred/Formula/awscred.rb
template: |
  class Awscred < Formula
    desc "A tool to generate a AWS session token and manage it easily."
    homepage "https://github.com/hanjunlee/awscred"
    version "$STABLE_VERSION"
    bottle :unneeded

    if OS.mac?
      url "$STABLE_ASSET_URL"
      sha256 "$STABLE_ASSET_SHA256"
    end

    def install
      bin.install "awscred"
    end

    test do
      system "awscred -v"
    end
  end
