---
kind: pipeline
type: docker
name: test

steps:
  - name: lint
    image: golang:1.13
    commands:
      - go vet ./...

  - name: unit-test
    image: golang:1.13
    commands:
      - go test -coverprofile=coverage.out ./...

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: master

steps:
  - name: lint
    image: golang:1.13
    commands:
      - go vet ./...

  - name: unit-test
    image: golang:1.13
    commands:
      - go test -coverprofile=coverage.out ./...

trigger:
  event:
    - push
  branch:
    - master
---
kind: pipeline
type: docker
name: release

steps:
  - name: download
    image: golang:1.13
    commands:
      - go mod download

  - name: build-darwin
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: darwin
      GOARCH: amd64
    commands:
      - mkdir darwin_amd64 && cp LICENSE README.md darwin_amd64
      - >
        go build 
        -o darwin_amd64/awscred
        -ldflags "-s -w -X github.com/hanjunlee/awscred/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/awscred/cmd.build=${DRONE_BUILD_NUMBER}" 
      - cd darwin_amd64 && tar -czf awscred_darwin_amd64.tar.gz awscred LICENSE README.md  
    depends_on:
      - download

  - name: build-linux
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    commands:
      - mkdir linux_amd64 && cp LICENSE README.md linux_amd64
      - >
        go build 
        -o linux_amd64/awscred
        -ldflags "-s -w -X github.com/hanjunlee/awscred/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/awscred/cmd.build=${DRONE_BUILD_NUMBER}" 
      - cd linux_amd64 && tar -czf awscred_linux_amd64.tar.gz awscred LICENSE README.md  
    depends_on:
      - download

  - name: build-windows
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
    commands:
      - mkdir windows_amd64 && cp LICENSE README.md windows_amd64
      - >
        go build 
        -o windows_amd64/awscred.exe 
        -ldflags "-s -w -X github.com/hanjunlee/awscred/cmd.commit=${DRONE_COMMIT} -X github.com/hanjunlee/awscred/cmd.build=${DRONE_BUILD_NUMBER}" 
      - cd windows_amd64 && tar -czf awscred_windows_amd64.tar.gz awscred.exe LICENSE README.md  
    depends_on:
      - download

  - name: aggregater
    image: golang:1.13
    commands:
      - mkdir dist
      - cp darwin_amd64/awscred_darwin_amd64.tar.gz linux_amd64/awscred_linux_amd64.tar.gz windows_amd64/awscred_windows_amd64.tar.gz dist/
      - ls dist/
    depends_on:
      - build-darwin
      - build-linux
      - build-windows

  - name: release
    image: plugins/github-release
    settings:
      title: ${DRONE_BRANCH}
      note: check [CHANGELOG.md](https://github.com/hanjunlee/awscred/blob/master/CHANGELOG.md).
      api_key: 
        from_secret: github_token
      files: dist/*
      checksum:
        - sha256
    depends_on:
      - aggregater

trigger:
  ref:
    - refs/tags/v*.*.*
